# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      bazel-modules:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      cargo-crates:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/bazel/btfdump"
    schedule:
      interval: "monthly"
    groups:
      btfdump-crates:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
