#!/bin/sh

# Script that allows running aarch64-linux-musl binaries using the provided
# sysroot as an execution environment.

set -eu

. "$(dirname -- "$0")/common.sh"

run_in_sysroot "${BPF_LINKER_SYSROOT_AARCH64_LINUX_MUSL}" "$@"
