name: CI

on:
  push:

  pull_request:

  release:
    types: [published]

  schedule:
    - cron: 00 4 * * *

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  llvm:
    permissions:
      # Needed to upload LLVM binaries as OCI artifacts to GHCR.
      packages: write
    runs-on: ${{ matrix.platform.os }}
    name: llvm
    outputs:
      cache-key: ${{ steps.cache-key.outputs.cache-key }}
    strategy:
      matrix:
        platform:
          - os: macos-latest
            target: aarch64-apple-darwin
            c-compiler: clang
            cxx-compiler: clang++
          - os: macos-15-intel
            target: x86_64-apple-darwin
            c-compiler: clang
            cxx-compiler: clang++
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            c-compiler: clang
            cxx-compiler: clang++
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl
            c-compiler: aarch64-linux-musl-clang
            cxx-compiler: aarch64-linux-musl-clang++
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            c-compiler: clang
            cxx-compiler: clang++
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
            c-compiler: x86_64-linux-musl-clang
            cxx-compiler: x86_64-linux-musl-clang++
        llvm:
          - version: 20
            git-ref: rustc/20.1-2025-02-13
          - version: 21
            git-ref: rustc/21.1-2025-08-01
          - version: 22
            git-ref: rustc/22.1-2026-01-27
    env:
      TAG_PREFIX: ghcr.io/${{ github.repository_owner }}/llvm
    steps:
      - id: ls-remote
        run: |
          set -euxo pipefail
          value=$(git ls-remote https://github.com/aya-rs/llvm-project.git refs/heads/${{ matrix.llvm.git-ref }} | cut -f1)
          echo "sha=$value" >> "$GITHUB_OUTPUT"

      - id: sha
        run: |
          set -euxo pipefail
          echo "sha=${{ steps.ls-remote.outputs.sha }}-1" >> "$GITHUB_OUTPUT"

      - uses: oras-project/setup-oras@v1

      - name: Login to ghcr.io
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          oras login ghcr.io --username "${{ github.actor }}" --password-stdin <<< "$GH_TOKEN"

      - name: Download LLVM artifact
        id: artifact-restore
        continue-on-error: true
        run: |
          oras pull "${{ env.TAG_PREFIX }}:${{ steps.sha.outputs.sha }}-${{ matrix.platform.target }}"

      - uses: actions/checkout@v6
        if: steps.artifact-restore.outcome != 'success'

      - uses: dtolnay/rust-toolchain@stable
        if: steps.artifact-restore.outcome != 'success'

      - name: Install Tools
        if: steps.artifact-restore.outcome != 'success' && runner.os == 'Linux'
        run: |
          set -euxo pipefail
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
            gpg --dearmor - | \
            sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | \
            sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null

          sudo apt update
          sudo apt -y install cmake ninja-build clang lld

      - name: Install tools
        if: steps.artifact-restore.outcome != 'success' && runner.os == 'macOS'
        run: |
          set -euxo pipefail
          brew bundle
          echo "$(brew --prefix lld)/bin" >> $GITHUB_PATH

      - name: Prepare sysroot
        if: steps.artifact-restore.outcome != 'success' && endsWith(matrix.platform.target, 'musl')
        run: |
          set -euxo pipefail
          sudo apt -y install bubblewrap
          target="${{ matrix.platform.target }}"
          arch="${target%%-*}"
          ./ci/prepare-musl-sysroot.py \
            "$arch" \
            sysroot >> $GITHUB_ENV
          echo "$(pwd)/ci" >> $GITHUB_PATH

      - name: Checkout LLVM Source
        if: steps.artifact-restore.outcome != 'success'
        uses: actions/checkout@v6
        with:
          repository: aya-rs/llvm-project
          ref: ${{ steps.ls-remote.outputs.sha }}
          path: llvm-project

      - name: Build LLVM
        if: steps.artifact-restore.outcome != 'success'
        run: |
          set -euxo pipefail
          target="${{ matrix.platform.target }}"
          arch="${target%%-*}"
          # `--system-name` is necessary to make CMake aware that we are cross
          # compiling.
          cargo xtask build-llvm \
            --src-dir llvm-project \
            --build-dir llvm-build \
            --install-prefix "${{ github.workspace }}/llvm-install" \
            --c-compiler "${{ matrix.platform.c-compiler }}" \
            --cxx-compiler "${{ matrix.platform.cxx-compiler }}" \
            ${{ endsWith(matrix.platform.target, 'musl') && format('--cmake-system-processor "$arch" --cmake-system-name Linux --sysroot {0}/sysroot', github.workspace) || '' }}

      - name: Package LLVM artifact
        if: steps.artifact-restore.outcome != 'success'
        run: |
          set -euxo pipefail
          tar --zstd -C "$GITHUB_WORKSPACE/llvm-install" -cf llvm-install.tar.zst .

      - name: Publish LLVM OCI artifact
        if: steps.artifact-restore.outcome != 'success'
        run: |
          set -euxo pipefail
          sha_tag="${{ env.TAG_PREFIX }}:${{ steps.sha.outputs.sha }}-${{ matrix.platform.target }}"
          version_tag="${{ env.TAG_PREFIX }}:${{ matrix.llvm.version }}-${{ matrix.platform.target }}"
          oras push "${sha_tag}" \
            --artifact-type application/vnd.aya.llvm.install \
            llvm-install.tar.zst:application/vnd.aya.llvm.install.layer.v1.tar+zstd
          oras tag "${sha_tag}" "${version_tag}"

  lint-stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rust-src

      - name: Run clippy
        run: cargo clippy --features llvm-22,no-llvm-linking --all-targets --workspace -- --deny warnings

  lint-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, rust-src

      - name: Check formatting
        run: cargo fmt --all -- --check

  build:
    permissions:
      # Needed to pull LLVM binaries as OCI artifacts from GHCR.
      packages: read
    runs-on: ${{ matrix.platform.os }}
    # We work with two git repositories in this workflow:
    #
    # - bpf-linker
    # - aya (for integration tests)
    #
    # Cargo searches for `.cargo` directories recursively in all parent
    # directories. Therefore, nesting different Rust projects with their own
    # `.cargo/config.toml` files in the same hierarchy (one nested in another)
    # causes cargo to read and merge both configurations.
    #
    # To avoid that, we clone both repositories in separate directories inside
    # the workspace.
    defaults:
      run:
        working-directory: bpf-linker
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - rust: 1.91.0
            llvm: 21
            exclude-features: default,llvm-19,llvm-20,llvm-22,rust-llvm-19,rust-llvm-20,rust-llvm-22
          - rust: stable
            llvm: 21
            exclude-features: default,llvm-19,llvm-20,llvm-22,rust-llvm-19,rust-llvm-20,rust-llvm-22
          - rust: beta
            llvm: 22
            exclude-features: llvm-20,llvm-21,rust-llvm-20,rust-llvm-21
          - rust: nightly
            llvm: 22
            exclude-features: llvm-20,llvm-21,rust-llvm-20,rust-llvm-21
        platform:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-15-intel
            target: x86_64-apple-darwin
          # We don't use ubuntu-latest because we care about the apt packages available.
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl
    name: target=${{ matrix.platform.target }} rustc=${{ matrix.toolchain.rust }} llvm=${{ matrix.toolchain.llvm }}
    needs: llvm

    env:
      RUST_BACKTRACE: full
      # Features that have to be included for dynamic linking.
      LLVM_FEATURES_DYNAMIC: llvm-${{ matrix.toolchain.llvm }}
      # Features that have to be included for static linking.
      LLVM_FEATURES_STATIC: llvm-${{ matrix.toolchain.llvm }},llvm-link-static
      # Features that have to be excluded when running `cargo hack --feature-powerset`
      # and intending to link dynamically.
      LLVM_EXCLUDE_FEATURES_DYNAMIC: llvm-link-static,no-llvm-linking

    steps:
      - uses: actions/checkout@v6
        with:
          path: bpf-linker

      - name: Install Rust ${{ matrix.toolchain.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain.rust }}
          targets: ${{ matrix.platform.target }}
          components: rust-src

      - name: Add clang to PATH
        if: runner.os == 'Linux'
        # ubuntu-22.04 comes with clang 13-15[0]; support for signed and 64bit
        # enum values was added in clang 15[1] which isn't in `$PATH`.
        #
        # [0] https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
        #
        # [1] https://github.com/llvm/llvm-project/commit/dc1c43d
        run: echo /usr/lib/llvm-15/bin >> $GITHUB_PATH

      - name: Prepare sysroot
        if: endsWith(matrix.platform.target, 'musl')
        run: |
          set -euxo pipefail
          sudo apt update
          sudo apt -y install bubblewrap
          target="${{ matrix.platform.target }}"
          arch="${target%%-*}"
          ./ci/prepare-musl-sysroot.py \
            "$arch" \
            sysroot \
            ${{ matrix.toolchain.rust }} >> $GITHUB_ENV
          echo "$(pwd)/ci" >> $GITHUB_PATH

      - name: Enforce dynamic linking
        run: echo "RUSTFLAGS=-C target-feature=-crt-static" >> $GITHUB_ENV

      - name: Check (default features, no system LLVM)
        run: cargo check --target ${{ matrix.platform.target }}

      - name: Build (default features, no system LLVM)
        run: cargo build --target ${{ matrix.platform.target }}

      - name: Install btfdump
        if: ${{ !endsWith(matrix.platform.target, 'musl') }}
        run: cargo install btfdump

      - uses: oras-project/setup-oras@v1

      - name: Login to ghcr.io
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          oras login ghcr.io --username "${{ github.actor }}" --password-stdin <<< "$GH_TOKEN"

      - name: Restore LLVM from ghcr.io
        run: |
          set -euxo pipefail
          ref="ghcr.io/${{ github.repository_owner }}/llvm:${{ matrix.toolchain.llvm }}-${{ matrix.platform.target }}"
          digest=$(oras manifest fetch "$ref" | jq -r '.layers[0].digest')
          # Make sure LLVM is available from the current directory, so
          # bubblewrap is able to access it. See the `ci/*-run` scripts.
          LLVM_INSTALL_DIR="$(pwd)/llvm-install"
          mkdir -p "$LLVM_INSTALL_DIR"
          oras blob fetch "${ref}@${digest}" --output - | tar --zstd -xf - -C "$LLVM_INSTALL_DIR"
          echo "${LLVM_INSTALL_DIR}/bin" >> $GITHUB_PATH

      # llvm-sys discovers link flags at build script time; these are cached by cargo. The cached
      # flags may be incorrect when the cache is reused across LLVM versions.
      - name: Bust llvm-sys cache
        run: |
          set -euxo pipefail
          cargo clean --target ${{ matrix.platform.target }} -p llvm-sys
          cargo clean --target ${{ matrix.platform.target }} -p llvm-sys --release

      - uses: taiki-e/install-action@cargo-hack

      - name: Check (dynamic linking, feature powerset)
        run: |
          cargo hack --target ${{ matrix.platform.target }} \
            check --feature-powerset --exclude-features \
            ${{ env.LLVM_EXCLUDE_FEATURES_DYNAMIC }},${{ matrix.toolchain.exclude-features }} \
            --features ${{ env.LLVM_FEATURES_DYNAMIC }}

      - name: Build (dynamic linking, feature powerset)
        run: |
          cargo hack --target ${{ matrix.platform.target }} \
            hack build --feature-powerset --exclude-features \
            ${{ env.LLVM_EXCLUDE_FEATURES_DYNAMIC }},${{ matrix.toolchain.exclude-features }} \
            --features ${{ env.LLVM_FEATURES_DYNAMIC }}

      # Toolchains provided by rustup include standard library artifacts
      # only for Tier 1 targets, which do not include BPF targets.
      #
      # The default workaround is to use the `rustc-build-sysroot` crate to
      # build a custom sysroot with the required BPF standard library before
      # running compiler tests.
      #
      # `RUSTC_BOOTSTRAP` is needed to use `rustc-build-sysroot` on stable Rust.
      - name: Test (sysroot built on demand, dynamic linking)
        run: |
          RUSTC_BOOTSTRAP=1 cargo hack --target ${{ matrix.platform.target }} \
            test --feature-powerset --exclude-features \
            ${{ env.LLVM_EXCLUDE_FEATURES_DYNAMIC }},${{ matrix.toolchain.exclude-features }} \
            --features ${{ env.LLVM_FEATURES_DYNAMIC }}

      # To make things easier for package maintainers, the step of building a
      # custom sysroot can be skipped by setting the `BPFEL_SYSROOT_DIR`
      # environment variable to the path of the prebuilt BPF sysroot.
      #
      # Test this configuration by prebuilding the BPF standard library
      # manually.
      #
      # `RUSTC_BOOTSTRAP` is needed to make `xtask build-std` work on stable
      # Rust.
      - name: Build BPF standard library
        run: |
          set -euxo pipefail

          RUSTC_SRC="$(rustc --print sysroot)/lib/rustlib/src/rust/library"
          BPFEL_SYSROOT_DIR="$(pwd)/bpf-sysroot"
          RUSTC_BOOTSTRAP=1 cargo xtask build-std \
            --rustc-src "$RUSTC_SRC" \
            --sysroot-dir "$BPFEL_SYSROOT_DIR" \
            --target bpfel-unknown-none

      - name: Test (prebuilt BPF standard libary, dynamic linking)
        run: |
          BPFEL_SYSROOT_DIR="$(pwd)/bpf-sysroot" \
            cargo hack --target ${{ matrix.platform.target }} test \
            --feature-powerset --exclude-features \
            ${{ env.LLVM_EXCLUDE_FEATURES_DYNAMIC }},${{ matrix.toolchain.exclude-features }} \
            --features ${{ env.LLVM_FEATURES_DYNAMIC }}

      - uses: actions/checkout@v6
        if: runner.os == 'Linux' && matrix.toolchain.rust == 'nightly'
        with:
          repository: aya-rs/aya
          path: aya
          submodules: recursive

      - name: Install (dynamic)
        if: endsWith(matrix.platform.target, 'gnu') && matrix.toolchain.rust == 'nightly'
        run: |
          cargo install --path . --no-default-features --features \
            ${{ env.LLVM_FEATURES_DYNAMIC }}

      # Even though we test both types of linking (dynamic, static) for musl
      # targets, installing a static bpf-linker for Aya integration tests is
      # just easier.
      - name: Install (static)
        if: endsWith(matrix.platform.target, 'musl') && matrix.toolchain.rust == 'nightly'
        env:
          RUSTFLAGS: -C target-feature=+crt-static
        run: |
          cargo install --target ${{ matrix.platform.target }} --path . \
            --no-default-features --features ${{ env.LLVM_FEATURES_STATIC }}

      - name: Install autopoint for aya integration tests
        if: runner.os == 'Linux' && matrix.toolchain.rust == 'nightly'
        run: sudo apt -y install autopoint

      - name: Run aya integration tests
        if: runner.os == 'Linux' && matrix.toolchain.rust == 'nightly'
        working-directory: aya
        run: cargo xtask integration-test local

      - name: Install static libraries (macOS)
        if: runner.os == 'macOS'
        # macOS does not provide any static libraries. Homebrew does provide
        # them, but in custom paths that the system-wide clang is not aware of.
        # Point build.rs to them by setting environment variables.
        #
        # We install llvm package only for libc++.
        #
        # libLLVM from homebrew requires zstd.
        run: |
          set -euxo pipefail
          brew bundle
          echo "CXXSTDLIB_PATH=$(brew --prefix llvm)/lib/c++" >> $GITHUB_ENV
          echo "LIBZSTD_PATH=$(brew --prefix zstd)/lib" >> $GITHUB_ENV
          echo "ZLIB_PATH=$(brew --prefix zlib)/lib" >> $GITHUB_ENV

      - name: Enforce static linking
        # Static linking with glibc is not supported.
        if: ${{ !endsWith(matrix.platform.target, 'gnu') }}
        run: echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV

      - name: Check (static linking, single feature set)
        if: ${{ !endsWith(matrix.platform.target, 'gnu') }}
        # Static linking in combination with `cargo hack --feature-powerset`
        # (multiple builds) increases the disk usage massively. Therefore we
        # perform all static builds with only one fixed feature set.
        run: |
          cargo check --target ${{ matrix.platform.target }} \
            --no-default-features --features ${{ env.LLVM_FEATURES_STATIC }}

      - name: Build (static linking, single feature set)
        if: ${{ !endsWith(matrix.platform.target, 'gnu') }}
        run: |
          cargo build --target ${{ matrix.platform.target }} \
            --no-default-features --features ${{ env.LLVM_FEATURES_STATIC }}

      - name: Test (sysroot built on demand, static linking)
        if: ${{ !endsWith(matrix.platform.target, 'gnu') }}
        run: |
          RUSTC_BOOTSTRAP=1 cargo test --target ${{ matrix.platform.target }} \
            --no-default-features --features ${{ env.LLVM_FEATURES_STATIC }}

      - name: Test (prebuilt BPF standard library, static linking)
        if: ${{ !endsWith(matrix.platform.target, 'gnu') }}
        run: |
          BPFEL_SYSROOT_DIR="$(pwd)/bpf-sysroot" \
            cargo test --target ${{ matrix.platform.target }} \
            --no-default-features --features ${{ env.LLVM_FEATURES_STATIC }}

      - name: Report disk usage
        if: ${{ always() }}
        uses: ./bpf-linker/.github/actions/report-disk-usage

  release:
    name: release
    needs: llvm
    runs-on: ${{ matrix.platform.os }}
    permissions:
      # This is used by the upload-rust-binary-action to upload the binary to the release.
      contents: write
    strategy:
      matrix:
        platform:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-15-intel
            target: x86_64-apple-darwin
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
            linker: x86_64-linux-musl-clang
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl
            linker: aarch64-linux-musl-clang
    env:
      LLVM_VERSION: 22
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - name: Install prerequisites
        if: runner.os == 'macOS'
        # macOS does not provide any static libraries. Homebrew does provide
        # them, but in custom paths that the system-wide clang is not aware of.
        # Point build.rs to them by setting environment variables.
        #
        # We install llvm package only for libc++.
        run: |
          set -euxo pipefail
          brew bundle
          echo "CXXSTDLIB_PATH=$(brew --prefix llvm)/lib/c++" >> $GITHUB_ENV
          echo "LIBZSTD_PATH=$(brew --prefix zstd)/lib" >> $GITHUB_ENV
          echo "ZLIB_PATH=$(brew --prefix zlib)/lib" >> $GITHUB_ENV

      - name: Prepare sysroot
        if: endsWith(matrix.platform.target, 'musl')
        run: |
          set -euxo pipefail
          sudo apt update
          sudo apt -y install bubblewrap
          target="${{ matrix.platform.target }}"
          arch="${target%%-*}"
          ./ci/prepare-musl-sysroot.py \
            "$arch" \
            sysroot \
            stable >> $GITHUB_ENV
          echo "$(pwd)/ci" >> $GITHUB_PATH

      - uses: oras-project/setup-oras@v1

      - name: Login to ghcr.io
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          oras login ghcr.io --username "${{ github.actor }}" --password-stdin <<< "$GH_TOKEN"

      - name: Restore LLVM from ghcr.io
        run: |
          set -euxo pipefail
          oras pull "ghcr.io/${{ github.repository_owner }}/llvm:${{ env.LLVM_VERSION }}-${{ matrix.platform.target }}"
          # Make sure LLVM is available from the current directory, so
          # bubblewrap is able to access it. See the `ci/*-run` scripts.
          LLVM_INSTALL_DIR="$(pwd)/llvm-install"
          mkdir -p "$LLVM_INSTALL_DIR"
          tar --zstd -xf llvm-install.tar.zst -C "$LLVM_INSTALL_DIR"
          rm -f llvm-install.tar.zst
          echo "${LLVM_INSTALL_DIR}/bin" >> $GITHUB_PATH

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: bpf-linker
          target: ${{ matrix.platform.target }}
          features: llvm-22,llvm-link-static
          no-default-features: true
          # By default, the action tries to use cross-rs when `target` is
          # defined. We want to use vanilla cargo, because we manage our own
          # clang wrappers and sysroots.
          build-tool: cargo
          dry-run: ${{ github.event_name != 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTFLAGS: ${{ matrix.platform.linker && format('-C linker={0}', matrix.platform.linker) || '' }} -C target-feature=+crt-static

      - name: Report disk usage
        if: ${{ always() }}
        uses: ./.github/actions/report-disk-usage
