name: Release

on:
  release:
    types: [published]

permissions: {}

env:
  BAZELISK_GITHUB_TOKEN: ${{ github.token }}
  BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Build release
        run: .github/workflows/build_release.sh

      - uses: actions/upload-artifact@v6
        with:
          name: bpf-linker-release
          path: dist/*

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${{ github.event.release.tag_name }}" dist/*
