name: Release

on:
  release:
    types: [published]
    
env:
  LLVM_SHA: 0b5eb7ba7bd796fb39c8bb6acd9ef6c140f28b65
  LLVM_TARGET: x86_64-unknown-linux-musl

jobs:
  upload-bins:
    # TODO: Build for macos someday.
    runs-on: ubuntu-22.04
    steps:
      - name: Install LLVM
        run: |
          set -euxo pipefail
          wget https://ci-artifacts.rust-lang.org/rustc-builds/${{ env.LLVM_SHA }}/rust-dev-nightly-${{ env.LLVM_TARGET }}.tar.xz
          tar -xpf rust-dev-nightly-${{ env.LLVM_TARGET }}.tar.xz --strip -C /opt
          echo /opt/rust-dev/bin >> $GITHUB_PATH

      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: bpf-linker
          features: llvm-sys/force-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
